-- Создание таблицы
CREATE TABLE IF NOT EXISTS weather_data (
    id SERIAL PRIMARY KEY,
    time TIMESTAMP WITH TIME ZONE UNIQUE,
    avg_temperature_2m_24h DECIMAL(10,4),
    avg_relative_humidity_2m_24h DECIMAL(10,4),
    avg_dew_point_2m_24h DECIMAL(10,4),
    avg_apparent_temperature_24h DECIMAL(10,4),
    avg_temperature_80m_24h DECIMAL(10,4),
    avg_temperature_120m_24h DECIMAL(10,4),
    avg_wind_speed_10m_24h DECIMAL(10,4),
    avg_wind_speed_80m_24h DECIMAL(10,4),
    avg_visibility_24h DECIMAL(10,4),
    total_rain_24h DECIMAL(10,4),
    total_showers_24h DECIMAL(10,4),
    total_snowfall_24h DECIMAL(10,4),
    avg_temperature_2m_daylight DECIMAL(10,4),
    avg_relative_humidity_2m_daylight DECIMAL(10,4),
    avg_dew_point_2m_daylight DECIMAL(10,4),
    avg_apparent_temperature_daylight DECIMAL(10,4),
    avg_temperature_80m_daylight DECIMAL(10,4),
    avg_temperature_120m_daylight DECIMAL(10,4),
    avg_wind_speed_10m_daylight DECIMAL(10,4),
    avg_wind_speed_80m_daylight DECIMAL(10,4),
    avg_visibility_daylight DECIMAL(10,4),
    total_rain_daylight DECIMAL(10,4),
    total_showers_daylight DECIMAL(10,4),
    total_snowfall_daylight DECIMAL(10,4),
    wind_speed_10m_m_per_s DECIMAL(10,4),
    wind_speed_80m_m_per_s DECIMAL(10,4),
    temperature_2m_celsius DECIMAL(10,4),
    apparent_temperature_celsius DECIMAL(10,4),
    temperature_80m_celsius DECIMAL(10,4),
    temperature_120m_celsius DECIMAL(10,4),
    soil_temperature_0cm_celsius DECIMAL(10,4),
    soil_temperature_6cm_celsius DECIMAL(10,4),
    rain_mm DECIMAL(10,4),
    showers_mm DECIMAL(10,4),
    snowfall_mm DECIMAL(10,4),
    daylight_hours DECIMAL(10,4),
    sunset_iso TIMESTAMP WITH TIME ZONE,
    sunrise_iso TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Создание индекса
CREATE INDEX IF NOT EXISTS idx_time ON weather_data(time);
