# .github/workflows/ci.yml

name: Debug Container Environment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  debug-container:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий, как и раньше
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Собираем образ. Этот шаг, похоже, работает нормально.
      - name: Build the Docker image
        run: docker compose build

      # 3. ЗАПУСКАЕМ ДИАГНОСТИКУ ВНУТРИ КОНТЕЙНЕРА
      - name: Inspect the built container
        run: |
          docker compose run --rm --no-deps --entrypoint /bin/sh etl-app -c "
            echo '--- 1. Current directory and files ---'
            pwd
            ls -la

            echo '--- 2. Checking installed pip packages ---'
            pip list

            echo '--- 3. Checking where Python looks for modules (sys.path) ---'
            python -c 'import sys; from pprint import pprint; pprint(sys.path)'
          "
