# .github/workflows/ci.yml

name: Run Python Tests

# Триггеры: запускать при push или pull request в основную ветку
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    # Запускать на последней версии Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование вашего репозитория на виртуальную машину
      # Вместе с кодом будет скопирован и ваш .env файл
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Запуск тестов с помощью Docker Compose
      # Он автоматически найдет и использует .env файл из вашего репозитория
      - name: Run tests with Docker Compose
        run: docker compose run --rm --entrypoint pytest etl-app
