# .github/workflows/ci.yml

name: Run Python Tests

# Триггеры: запускать при push или pull request в основную ветку
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование вашего репозитория на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Запуск тестов с помощью Docker Compose
      # Эта команда в точности повторяет ту, что вы используете локально.
      - name: Run tests with Docker Compose
        run: docker compose run --rm --entrypoint pytest etl-app
